name: flutter_session_manager
description: Easy to use session wrapper that adds support to session storage and management in flutter.
version: 1.0.1
homepage:
issue_tracker: https://github.com/edumigueis/flutter_session_manager/issues
repository: https://github.com/edumigueis/flutter_session_manager

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: